import { useState } from 'react';
import Deck from './deck/Deck';
import Slide from './deck/Slide';
import Build from './deck/Build';
import Cover from './components/Cover';
import BigNumber from './components/BigNumber';
import raw from './data/public-aggregates.json';
import './styles/report.css';
import reasons from './data/public-reasons.json';
const reasonCount=(scope:string,category:string)=>reasons.find(r=>r.scope===scope&&r.category===category)?.count??0;
const details:Record<string,{cause:string,action:string}>={
 'LiLA anak':{cause:'Lingkar lengan atas anak memicu tanda perhatian gizi pada data sumber.',action:'Ukur ulang LiLA dengan teknik yang benar; hasil yang tetap berisiko dinilai bidan atau puskesmas.'},
 'Usia anak':{cause:'Usia yang tercatat tidak sesuai dengan perhitungan dari tanggal lahir.',action:'Cocokkan tanggal lahir dengan dokumen keluarga dan tanggal pemeriksaan; hitung ulang usia.'},
 'IMT ibu':{cause:'Indeks massa tubuh memicu tanda di luar kisaran pada data sumber; bukan diagnosis.',action:'Periksa tinggi, berat dan satuannya; ukur ulang, lalu minta penilaian tenaga kesehatan.'},
 'Tekanan darah ibu':{cause:'Catatan tekanan darah memicu tanda perlu tinjau; dapat berupa hasil berisiko atau input yang meragukan.',action:'Ulangi pengukuran dengan prosedur yang benar dan cocokkan input. Bidan atau puskesmas menilai hasil klinis.'},
 'LiLA ibu':{cause:'Lingkar lengan atas ibu memicu tanda perhatian pada data sumber.',action:'Ukur ulang dan arahkan penilaian gizi kepada bidan atau puskesmas.'},
 'Urutan tekanan darah':{cause:'Ada catatan bertanda tinjau dengan sistolik lebih rendah daripada diastolik. Ini perlu verifikasi, bukan diagnosis.',action:'Cocokkan urutan kolom dengan alat dan catatan asli, lalu ulangi pengukuran sebelum menarik kesimpulan.'}
};
function ReasonDetail({keys}:{keys:string[]}){const [selected,setSelected]=useState(keys[0]);return <div className="reason-detail mat"><div className="reason-tabs">{keys.map(k=><button key={k} aria-pressed={selected===k} onClick={()=>setSelected(k)}>{k}</button>)}</div><div className="reason-answer" aria-live="polite"><h3>{selected}</h3><p><b>Mengapa ditandai:</b> {details[selected].cause}</p><p><b>Langkah desa:</b> {details[selected].action}</p></div></div>;}

type Row = typeof raw[number];
type Metric = 'total'|'perlu_tinjau'|'kuning'|'merah'|'valid';
const months = ['2026-06','2026-07','2026-08'];
const monthLabel: Record<string,string> = {'2026-06':'Juni','2026-07':'Juli','2026-08':'Agustus'};
const sum = (rows: Row[], key: Metric = 'total') => rows.reduce((s,r)=>s+r[key],0);
function Bars({items,color='var(--primary)'}:{items:{label:string,value:number}[],color?:string}) {
 const max=Math.max(1,...items.map(i=>i.value));
 return <div className="bars" role="img" aria-label={items.map(i=>`${i.label}: ${i.value}`).join('; ')}>{items.map(i=><div className="bar-row" key={i.label}><span>{i.label}</span><div className="bar-track"><div className="bar-fill" style={{width:`${i.value/max*100}%`,background:color}} /></div><strong>{i.value}</strong></div>)}</div>;
}
export default function App(){
 const [month,setMonth]=useState('all'), [role,setRole]=useState('all'), [test,setTest]=useState(true);
 const rows=raw.filter(r=>(month==='all'||r.month===month)&&(role==='all'||r.role===role)&&(test||r.anonymous_code!=='account-test'));
 const actors=Array.from(new Set(rows.map(r=>r.anonymous_code))).sort((a,b)=>sum(rows.filter(r=>r.anonymous_code===b))-sum(rows.filter(r=>r.anonymous_code===a)));
 const groups=(keys:string[],field:'month'|'jenis'|'anonymous_code',metric:Metric='total')=>keys.map(k=>({label:field==='month'?monthLabel[k]:k,value:sum(rows.filter(r=>r[field]===k),metric)}));
 const filters=<div className="filters"><label>Bulan<select aria-label="Bulan" value={month} onChange={e=>setMonth(e.target.value)}><option value="all">Semua bulan</option>{months.map(m=><option key={m} value={m}>{monthLabel[m]} 2026</option>)}</select></label><label>Peran<select aria-label="Peran" value={role} onChange={e=>setRole(e.target.value)}><option value="all">Semua peran</option><option value="KADER">Kader</option><option value="ADMIN">Admin</option></select></label><label className="test-filter"><input aria-label="Sertakan account-test" type="checkbox" checked={test} onChange={e=>setTest(e.target.checked)}/>account-test</label><span className="scope" data-testid="filtered-total">{sum(rows)} input</span></div>;
 const head=(k:string,title:string,desc:string)=><header className="report-head"><span className="kicker">{k}</span><h2>{title}</h2><p>{desc}</p></header>;
 return <Deck>
 <Cover nav="Pembuka" kicker="KB-Glow / Laporan agregat" title={<>Laporan pencatatan<br/><span className="accent-text">KB-GLOWING.</span></>} subtitle="Juni–Agustus 2026 · jumlah pencatatan, aktivitas petugas, dan hasil yang perlu perhatian." foot="Data dirangkum pada 1 Oktober 2026 · nama petugas disamarkan" />
 <BigNumber nav="216 input" kicker="Jumlah pencatatan" value="216" caption="pencatatan pemeriksaan; satu orang dapat dicatat lebih dari sekali" foot="Data yang tidak dihapus: pemeriksaan anak, pengukuran ibu, dan skrining Hb" />
 <Slide center nav="Ringkasan">{head('01 / Ikhtisar','Ringkasan hasil pencatatan','Pilih bulan dan jenis petugas untuk melihat bagian data yang diinginkan. Tampilan awal termasuk admin dan akun uji.')}{filters}<div className="metrics">{(['total','perlu_tinjau','kuning','merah','valid'] as Metric[]).map((m,i)=><div className="metric mat" key={m}><b data-testid={`metric-${m}`}>{sum(rows,m)}</b><span>{['Input','Perlu tinjau','Kuning','Merah','Valid'][i]}</span></div>)}</div><p className="caption">Baru 1 pencatatan memiliki tanda validasi pada data yang diperiksa. Pencatatan lainnya belum tentu salah; tanda validasi tidak menunjukkan seluruh hasil pemeriksaan.</p></Slide>
 <Slide center nav="Input bulanan">{head('02 / Ritme input','Agustus mendominasi volume','Bulan menunjukkan kapan data masuk ke server, bukan selalu kapan pemeriksaan dilakukan.')}{filters}<div className="chart-panel mat"><Bars items={groups(months,'month')}/></div><p className="caption">Dari 216 pencatatan, 163 masuk pada Agustus (75,5%). Juni 3 dan Juli 50. Angka ini menunjukkan aktivitas pencatatan, bukan perubahan kesehatan warga.</p></Slide>
 <Slide center nav="Sinyal bulanan">{head('03 / Tindak lanjut','Hasil yang perlu perhatian','Perlu tinjau berarti data perlu diperiksa kembali. Kuning dan merah menunjukkan kategori risiko yang tercatat.')}{filters}<div className="signal-grid">{(['perlu_tinjau','kuning','merah'] as Metric[]).map((m,i)=><section className="chart-panel mat" key={m}><h3>{['Perlu tinjau','Kuning','Merah'][i]}</h3><Bars items={groups(months,'month',m)} color={['var(--primary)','var(--warning)','var(--risk)'][i]}/></section>)}</div></Slide>
 <Slide center nav="Kontribusi">{head('04 / Pelaksana','Jumlah pencatatan per petugas','Petugas dengan pencatatan terbanyak tampil di atas. Banyaknya pencatatan bukan ukuran ketepatan atau mutu kerja.')}{filters}<div className="chart-panel mat actor-panel"><Bars items={actors.map(a=>({label:`${a} · ${rows.find(r=>r.anonymous_code===a)?.role}`,value:sum(rows.filter(r=>r.anonymous_code===a))}))}/>{!actors.length&&<p>Tidak ada input pada kombinasi filter ini.</p>}</div></Slide>
 <Slide center nav="Heatmap">{head('05 / Aktivitas bulanan','Aktivitas petugas setiap bulan','Angka menunjukkan jumlah pencatatan. Sel dengan warna lebih terang berarti lebih banyak pencatatan pada bulan tersebut.')}{filters}<div className="heatmap mat"><div className="heat-row heat-header"><span>Pelaksana</span>{months.map(m=><span key={m}>{monthLabel[m]}</span>)}</div>{actors.map(a=><div className="heat-row" key={a}><span>{a}</span>{months.map(m=>{const n=sum(rows.filter(r=>r.anonymous_code===a&&r.month===m));return <span key={m} style={{background:`color-mix(in srgb, var(--primary) ${Math.min(80,8+n)}%, transparent)`}} aria-label={`${a}, ${monthLabel[m]}: ${n}`}>{n}</span>})}</div>)}{!actors.length&&<p>Tidak ada input.</p>}</div></Slide>
 <Slide center nav="Jenis input">{head('06 / Layanan','Tiga jenis pencatatan','Terdapat 147 pencatatan anak, 33 pengukuran ibu, dan 36 skrining Hb pada seluruh data.')}{filters}<div className="chart-panel mat"><Bars items={groups(['Anak','Ibu','Hb'],'jenis')}/></div><p className="caption">Pencatatan anak merupakan bagian terbesar (68,1%). Satu orang dapat memiliki lebih dari satu pencatatan; angka ini bukan jumlah warga.</p></Slide>
 <Slide center nav="Cara membaca">{head('07 / Penjelasan','Apa arti angka perhatian?','22 pencatatan perlu ditinjau, 38 berstatus kuning, dan 39 berstatus merah.')}<div className="explain mat"><h3>Jangan menjumlahkan ketiga angka</h3><p>Satu pencatatan dapat sekaligus perlu ditinjau dan memiliki status risiko. Karena itu, ketiga angka tidak dapat dijumlahkan menjadi jumlah orang atau kasus.</p><p>Kuning dan merah bukan berarti kader salah menginput. Angka tersebut menunjukkan hasil yang perlu perhatian sesuai kategori pada data sumber.</p></div><Build at={1}><p className="caption">Laporan ini menjelaskan pencatatan yang tersedia, bukan menetapkan diagnosis kesehatan.</p></Build></Slide>
 <Slide center nav="Alasan anak">{head('08 / Alasan tinjau','6 dari 147 catatan anak perlu tinjau','Alasan yang masih aktif pada snapshot 1 Oktober 2026. Klik kategori untuk langkah desa.')}<div className="chart-panel mat reason-chart"><Bars items={['LiLA','Usia'].map(c=>({label:c,value:reasonCount('Anak',c)}))}/></div><ReasonDetail keys={['LiLA anak','Usia anak']}/><p className="caption">Jumlah pencatatan, bukan orang. Tanpa identitas, nilai pemeriksaan, atau rincian desa.</p></Slide>
 <Slide center nav="Alasan ibu">{head('09 / Alasan tinjau','16 dari 33 catatan ibu perlu tinjau','Kategori saling tumpang tindih: satu catatan dapat memiliki beberapa alasan.')}<div className="chart-panel mat reason-chart"><Bars items={['IMT','Tekanan darah','LiLA'].map(c=>({label:c,value:reasonCount('Ibu',c)}))}/></div><ReasonDetail keys={['IMT ibu','Tekanan darah ibu','LiLA ibu','Urutan tekanan darah']}/><p className="caption">{reasonCount('Ibu','Urutan tekanan darah perlu verifikasi')} catatan bertanda tinjau memiliki urutan tekanan darah yang perlu verifikasi; bagian dari kelompok ibu, bukan tambahan kasus.</p></Slide>
 <Slide center nav="Langkah desa">{head('10 / Tindak lanjut desa','Verifikasi data, lanjutkan penilaian','6 dari 36 skrining Hb tercatat berisiko. Rincian tingkat keparahan tidak dipublikasikan.')}<div className="chart-panel mat reason-chart"><Bars items={[{label:'Risiko Hb',value:reasonCount('Hb','Risiko Hb')}]} color="var(--warning)"/></div><div className="explain mat followup"><h3>1 · Kader dan keluarga</h3><p>Cocokkan tanggal lahir dan catatan pemeriksaan; ulangi pengukuran atau input yang meragukan.</p><h3>2 · Bidan atau puskesmas</h3><p>Evaluasi hasil klinis yang ditandai, termasuk Hb, dan tentukan pemeriksaan serta tindak lanjut sesuai penilaian tenaga kesehatan.</p><h3>3 · Bila ada gejala berat</h3><p>Segera cari pertolongan tenaga kesehatan yang berwenang; jangan menunggu verifikasi laporan.</p></div><p className="caption">6 risiko Hb bukan keseluruhan 38 kuning dan 39 merah lintas layanan. Tanda saat ini bukan riwayat maupun diagnosis.</p></Slide>
 <Slide center nav="Tentang data">{head('11 / Cakupan laporan','Data apa yang dihitung?','Ringkasan dibuat pada 1 Oktober 2026 dari pencatatan Juni–Agustus 2026.')}<div className="explain mat"><p>Laporan mencakup pemeriksaan anak, pengukuran ibu, dan skrining Hb yang tidak dihapus. Kunjungan keluarga dan layanan lain tidak termasuk.</p><p>Admin menyumbang 82 pencatatan; akun berperan kader menyumbang 134, termasuk 32 dari akun yang dikenali sebagai akun uji. Filter dapat memisahkan bagian tersebut.</p><p>Data setelah ringkasan dibuat tidak otomatis masuk ke laporan. Nama petugas disamarkan; tidak ada nama pasien atau hasil pemeriksaan per orang.</p></div><p className="caption">Tanda perlu tinjau yang sudah dihapus setelah pemeriksaan ulang tidak dapat dibaca sebagai riwayat dari ringkasan ini.</p></Slide>
 <Slide center nav="Kesimpulan">{head('12 / Kesimpulan','Pencatatan paling banyak pada Agustus','Kesimpulan ini menggunakan seluruh data, sebelum filter bulan atau petugas diterapkan.')}<div className="explain mat"><h3>216 pencatatan, bukan 216 orang</h3><p>Sebanyak 163 pencatatan (75,5%) masuk pada Agustus. Pemeriksaan anak paling banyak: 147 pencatatan (68,1%).</p><h3>Ada hasil yang perlu perhatian</h3><p>Terdapat 22 pencatatan perlu tinjau, 38 kuning dan 39 merah. Angka ini tidak boleh dijumlahkan dan bukan ukuran kesalahan kader.</p><h3>Tindak lanjut bersama di desa</h3><p>Kader mencocokkan tanggal lahir dan mengulang data meragukan. Bidan atau puskesmas mengevaluasi hasil berisiko dan menentukan tindak lanjut; gejala berat memerlukan pertolongan segera.</p></div><Build at={1}><p className="caption">Angka menunjukkan aktivitas dan hasil yang tercatat; belum cukup untuk menyimpulkan perubahan kondisi kesehatan masyarakat.</p></Build></Slide>
 </Deck>;
}
