import { useState } from 'react';
import Deck from './deck/Deck';
import Slide from './deck/Slide';
import Build from './deck/Build';
import Cover from './components/Cover';
import BigNumber from './components/BigNumber';
import raw from './data/public-aggregates.json';
import './styles/report.css';

type Row = typeof raw[number];
type Metric = 'total'|'perlu_tinjau'|'kuning'|'merah'|'valid';
const months = ['2026-06','2026-07','2026-08'];
const monthLabel: Record<string,string> = {'2026-06':'Juni','2026-07':'Juli','2026-08':'Agustus'};
const sum = (rows: Row[], key: Metric = 'total') => rows.reduce((s,r)=>s+r[key],0);
function Bars({items,color='var(--primary)'}:{items:{label:string,value:number}[],color?:string}) {
 const max=Math.max(1,...items.map(i=>i.value));
 return <div className="bars" role="img" aria-label={items.map(i=>`${i.label}: ${i.value}`).join('; ')}>{items.map(i=><div className="bar-row" key={i.label}><span>{i.label}</span><div className="bar-track"><div className="bar-fill" style={{width:`${i.value/max*100}%`,background:color}} /></div><strong>{i.value}</strong></div>)}</div>;
}
export default function App(){
 const [month,setMonth]=useState('all'), [role,setRole]=useState('all'), [test,setTest]=useState(true);
 const rows=raw.filter(r=>(month==='all'||r.month===month)&&(role==='all'||r.role===role)&&(test||r.anonymous_code!=='account-test'));
 const actors=Array.from(new Set(rows.map(r=>r.anonymous_code))).sort((a,b)=>sum(rows.filter(r=>r.anonymous_code===b))-sum(rows.filter(r=>r.anonymous_code===a)));
 const groups=(keys:string[],field:'month'|'jenis'|'anonymous_code',metric:Metric='total')=>keys.map(k=>({label:field==='month'?monthLabel[k]:k,value:sum(rows.filter(r=>r[field]===k),metric)}));
 const filters=<div className="filters"><label>Bulan<select aria-label="Bulan" value={month} onChange={e=>setMonth(e.target.value)}><option value="all">Semua bulan</option>{months.map(m=><option key={m} value={m}>{monthLabel[m]} 2026</option>)}</select></label><label>Peran<select aria-label="Peran" value={role} onChange={e=>setRole(e.target.value)}><option value="all">Semua peran</option><option value="KADER">Kader</option><option value="ADMIN">Admin</option></select></label><label className="test-filter"><input aria-label="Sertakan account-test" type="checkbox" checked={test} onChange={e=>setTest(e.target.checked)}/>account-test</label><span className="scope" data-testid="filtered-total">{sum(rows)} input</span></div>;
 const head=(k:string,title:string,desc:string)=><header className="report-head"><span className="kicker">{k}</span><h2>{title}</h2><p>{desc}</p></header>;
 return <Deck>
 <Cover nav="Pembuka" kicker="KB-Glow / Laporan agregat" title={<>Aktivitas nyata.<br/><span className="accent-text">Identitas terlindungi.</span></>} subtitle="Juni–Agustus 2026 · eksplorasi input, kontribusi, dan sinyal tindak lanjut." foot="Snapshot agregat · anonim · bukan data pasien atau dashboard langsung" />
 <BigNumber nav="216 input" kicker="Cakupan snapshot" value="216" caption="input tercatat, bukan 216 pasien unik" foot="Agregat non-deleted: Anak, pengukuran Ibu, skrining Hb · Juni–Agustus 2026" />
 <Slide center nav="Ringkasan">{head('01 / Ikhtisar','Volume bukan kualitas','Filter berikut berlaku pada seluruh grafik laporan. Angka awal mencakup semua peran dan akun uji.')}{filters}<div className="metrics">{(['total','perlu_tinjau','kuning','merah','valid'] as Metric[]).map((m,i)=><div className="metric mat" key={m}><b data-testid={`metric-${m}`}>{sum(rows,m)}</b><span>{['Input','Perlu tinjau','Kuning','Merah','Valid'][i]}</span></div>)}</div><p className="caption">Valid: Ibu memakai validated_at; Anak/Hb memakai validation_status. Hanya 1 pada snapshot, bukan berarti seluruh input lain salah.</p></Slide>
 <Slide center nav="Input bulanan">{head('02 / Ritme input','Agustus mendominasi volume','Bulan mengikuti created_at dalam WITA, bukan tanggal pemeriksaan.')}{filters}<div className="chart-panel mat"><Bars items={groups(months,'month')}/></div><p className="caption">Baseline seluruh data: Juni 3 · Juli 50 · Agustus 163. Tidak ada data bulan lain dalam subset ini.</p></Slide>
 <Slide center nav="Sinyal bulanan">{head('03 / Tindak lanjut','Pisahkan flag dari risiko','Tiga seri ditampilkan berdampingan, bukan ditumpuk atau dijumlahkan sebagai pasien unik.')}{filters}<div className="signal-grid">{(['perlu_tinjau','kuning','merah'] as Metric[]).map((m,i)=><section className="chart-panel mat" key={m}><h3>{['Perlu tinjau','Kuning','Merah'][i]}</h3><Bars items={groups(months,'month',m)} color={['var(--primary)','var(--warning)','var(--risk)'][i]}/></section>)}</div></Slide>
 <Slide center nav="Kontribusi">{head('04 / Pelaksana','Kontribusi tanpa identitas','Urutan berdasarkan jumlah input dalam filter aktif; role asli tetap dipertahankan.')}{filters}<div className="chart-panel mat actor-panel"><Bars items={actors.map(a=>({label:`${a} · ${rows.find(r=>r.anonymous_code===a)?.role}`,value:sum(rows.filter(r=>r.anonymous_code===a))}))}/>{!actors.length&&<p>Tidak ada input pada kombinasi filter ini.</p>}</div></Slide>
 <Slide center nav="Heatmap">{head('05 / Matriks bulanan','Siapa aktif, kapan?','Sel terang menunjukkan volume relatif, angka menunjukkan jumlah input sebenarnya.')}{filters}<div className="heatmap mat"><div className="heat-row heat-header"><span>Pelaksana</span>{months.map(m=><span key={m}>{monthLabel[m]}</span>)}</div>{actors.map(a=><div className="heat-row" key={a}><span>{a}</span>{months.map(m=>{const n=sum(rows.filter(r=>r.anonymous_code===a&&r.month===m));return <span key={m} style={{background:`color-mix(in srgb, var(--primary) ${Math.min(80,8+n)}%, transparent)`}} aria-label={`${a}, ${monthLabel[m]}: ${n}`}>{n}</span>})}</div>)}{!actors.length&&<p>Tidak ada input.</p>}</div></Slide>
 <Slide center nav="Jenis input">{head('06 / Layanan','Tiga jenis pencatatan','Input Anak, pengukuran Ibu, dan skrining Hb dihitung sebagai aktivitas, bukan populasi unik.')}{filters}<div className="chart-panel mat"><Bars items={groups(['Anak','Ibu','Hb'],'jenis')}/></div><p className="caption">Jenis tidak otomatis menunjukkan jumlah keluarga atau pasien. Satu orang dapat memiliki beberapa pencatatan.</p></Slide>
 <Slide center nav="Cara membaca">{head('07 / Interpretasi','Jangan menjumlahkan sinyal','Perlu tinjau adalah flag alur verifikasi. Kuning dan merah adalah kategori risiko pada snapshot.')}<div className="explain mat"><h3>22 flag ≠ 22 kasus tambahan</h3><p>Flag dapat beririsan dengan risiko. Subset agregat tidak menyimpan matriks irisan per record, sehingga jumlah unik gabungan tidak dapat dihitung.</p><p>Kuning 38 dan merah 39 dibaca sesuai kategori sumber; laporan ini tidak memberi diagnosis atau menetapkan tindak klinis.</p></div><Build at={1}><p className="caption">Prioritas: konfirmasi definisi indikator, audit data sumber, lalu tindak lanjut oleh petugas berwenang.</p></Build></Slide>
 <Slide center nav="Batas snapshot">{head('08 / Transparansi','Potret terbatas, bukan tren klinis','Ekstraksi lokal: 2026-10-01T17:42:28.201238 (zona timestamp tidak dicantumkan). Aktivitas: Juni–Agustus 2026.')}<div className="explain mat"><p>Lingkup: record non-deleted untuk Anak, pengukuran Ibu dan skrining Hb. Pengelompokan bulan dari created_at WITA; data diperbarui setelah snapshot tidak tercermin.</p><p>Semua peran termasuk admin dapat dipilih terpisah. account-test dikenali secara heuristik dari label akun sumber, tetap berperan KADER. Akun lain tidak otomatis terverifikasi sebagai produksi.</p><p>Kode Petugas stabil dalam rilis ini, bukan identitas publik. Tidak ada nama asli, ID aktor, data pasien, kredensial atau berkas mentah.</p></div><p className="caption">Emerald gelap adalah palet laporan sesuai arahan, bukan klaim identitas resmi merek KB-Glow.</p></Slide>
 <Slide center nav="Langkah berikut">{head('09 / Rekomendasi','Rapikan sistem, bukan hanya grafik','Usulan berikut belum diimplementasikan pada aplikasi KB-Glow.')}<div className="explain mat"><h3>1. Pisahkan lingkungan uji</h3><p>Tandai akun uji secara eksplisit dan keluarkan dari laporan operasional default.</p><h3>2. Tegaskan definisi & audit</h3><p>Dokumentasikan flag verifikasi, kategori risiko, irisan, serta jejak perubahan status.</p><h3>3. Bangun pelaporan terkelola</h3><p>Bedakan tanggal input dan layanan, sediakan deduplikasi terotorisasi dan ekspor anonim dengan kontrol akses.</p></div><Build at={1}><p className="caption">Tindak lanjut: validasi definisi bersama pengelola sebelum mengambil keputusan layanan.</p></Build></Slide>
 </Deck>;
}
